# Generated by Django 3.0.3 on 2020-04-16 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forgatetoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('otp', models.IntegerField()),
                ('cont', models.IntegerField(default=1)),
            ],
        ),
    ]
