# Generated by Django 3.0.3 on 2020-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('ac_id', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
