# Generated by Django 3.0.3 on 2020-02-22 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today)),
                ('number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('rs', models.IntegerField()),
                ('status', models.IntegerField()),
                ('through', models.CharField(blank=True, max_length=150, null=True)),
                ('payment', models.CharField(blank=True, max_length=150, null=True)),
                ('cb', models.IntegerField(default=0)),
                ('apc', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('p_np', models.CharField(max_length=50)),
                ('ac_id', models.CharField(blank=True, max_length=50, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshot')),
            ],
        ),
    ]
